### ISSUE TITLE
auto-rename legacy settings

### ISSUE THREAD

**Issue by FlorianDoerr** [viperleed/viperleed#256] opened 2024-10-09 13:24 UTC
Add a method to the ViPErLEEDSettings class that searches through detected invalid settings for old values and replaces deprecated ones. This will spare us adding a backwards-compatibility fix whenever we change the name of an option in the .ini files.

**Comment by michele-riva** [comment] 2024-10-09 13:27
Is this a duplicate of #242? If yes, I'd keep the earlier one and close this one as duplicate

**Closed** 2024-10-09 13:53 UTC
Labels: enhancement, GUI:measurement, nice-to-have, backwards-compatibility
